server:
  port: 8010

spring:
  application:
    name: gateway

  cloud:
    gateway:
      mvc:
        routes:
          # AUTENTICACION
          - id: servicio-autenticacion
            uri: lb://servicio-autenticacion
            predicates:
              - Path=/autenticacion/**

          # CLIENTES
          - id: servicio-cliente
            uri: lb://servicio-cliente
            predicates:
              - Path=/clientes/**

          # TICKETS
          - id: servicio-tickets
            uri: lb://servicio-tickets
            predicates:
              - Path=/tickets/**

          # PROYECTOS
          - id: servicio-proyectos
            uri: lb://servicio-proyectos
            predicates:
              - Path=/proyectos/**

          # REUNIONES
          - id: servicio-reuniones
            uri: lb://servicio-reuniones
            predicates:
              - Path=/reuniones/**

          # FACTURACION
          - id: servicio-facturas
            uri: lb://servicio-facturas
            predicates:
              - Path=/facturas/**

          # REPORTES
          - id: servicio-reportes
            uri: lb://servicio-reportes
            predicates:
              - Path=/reportes/**

          # AUDITORIA
          - id: servicio-auditoria
            uri: lb://servicio-auditoria
            predicates:
              - Path=/auditorias/**

          # NOTIFICACIONES
          - id: servicio-notificaciones
            uri: lb://servicio-notificaciones
            predicates:
              - Path=/notificaciones/**

  # Configuración de Eureka para el Gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}